/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CommentDTO,
  Page
} from '../msocial.schemas';


export const getGetCommentResponseMock = (overrideResponse: Partial<Extract<CommentDTO, object>> = {}): CommentDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), postId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), parentId: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['PUBLISHED','DELETED','HIDDEN'] as const), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUpdateCommentResponseMock = (overrideResponse: Partial<Extract<CommentDTO, object>> = {}): CommentDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), postId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), parentId: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['PUBLISHED','DELETED','HIDDEN'] as const), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getGetCommentsResponseMock = (overrideResponse: Partial<Extract<Page, object>> = {}): Page => ({totalElements: faker.helpers.arrayElement([faker.number.int(), undefined]), totalPages: faker.helpers.arrayElement([faker.number.int(), undefined]), first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), numberOfElements: faker.helpers.arrayElement([faker.number.int(), undefined]), pageable: faker.helpers.arrayElement([{paged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int(), undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), unpaged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), offset: faker.helpers.arrayElement([faker.number.int(), undefined])}, undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({})), undefined]), number: faker.helpers.arrayElement([faker.number.int(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getCreateCommentResponseMock = (overrideResponse: Partial<Extract<CommentDTO, object>> = {}): CommentDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), postId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), parentId: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['PUBLISHED','DELETED','HIDDEN'] as const), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getGetRepliesResponseMock = (overrideResponse: Partial<Extract<Page, object>> = {}): Page => ({totalElements: faker.helpers.arrayElement([faker.number.int(), undefined]), totalPages: faker.helpers.arrayElement([faker.number.int(), undefined]), first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), numberOfElements: faker.helpers.arrayElement([faker.number.int(), undefined]), pageable: faker.helpers.arrayElement([{paged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int(), undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), unpaged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), offset: faker.helpers.arrayElement([faker.number.int(), undefined])}, undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({})), undefined]), number: faker.helpers.arrayElement([faker.number.int(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})


export const getGetCommentMockHandler = (overrideResponse?: CommentDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CommentDTO> | CommentDTO), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/comments/:commentId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCommentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateCommentMockHandler = (overrideResponse?: CommentDTO | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CommentDTO> | CommentDTO), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/comments/:commentId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCommentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteCommentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/comments/:commentId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetCommentsMockHandler = (overrideResponse?: Page | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Page> | Page), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/posts/:postId/comments', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCommentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateCommentMockHandler = (overrideResponse?: CommentDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CommentDTO> | CommentDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/posts/:postId/comments', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCommentResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetRepliesMockHandler = (overrideResponse?: Page | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Page> | Page), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/comments/:commentId/replies', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRepliesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getCommentsMock = () => [
  getGetCommentMockHandler(),
  getUpdateCommentMockHandler(),
  getDeleteCommentMockHandler(),
  getGetCommentsMockHandler(),
  getCreateCommentMockHandler(),
  getGetRepliesMockHandler()]
