/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CommentDTO,
  CreateCommentRequest,
  Page,
  UpdateCommentRequest
} from '../msocial.schemas';




  export const getComments = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Получить комментарий по ID
 */
const getComment = (
    commentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CommentDTO>> => {
    return axiosInstance.get(
      `/api/v1/comments/${commentId}`,options
    );
  }
/**
 * @summary Обновить комментарий
 */
const updateComment = (
    commentId: number,
    updateCommentRequest: UpdateCommentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CommentDTO>> => {
    return axiosInstance.put(
      `/api/v1/comments/${commentId}`,
      updateCommentRequest,options
    );
  }
/**
 * @summary Удалить комментарий
 */
const deleteComment = (
    commentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/comments/${commentId}`,options
    );
  }
/**
 * @summary Получить комментарии к посту
 */
const getComments = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Page>> => {
    return axiosInstance.get(
      `/api/v1/posts/${postId}/comments`,options
    );
  }
/**
 * @summary Создать комментарий к посту
 */
const createComment = (
    postId: number,
    createCommentRequest: CreateCommentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CommentDTO>> => {
    return axiosInstance.post(
      `/api/v1/posts/${postId}/comments`,
      createCommentRequest,options
    );
  }
/**
 * @summary Получить ответы на комментарий
 */
const getReplies = (
    commentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Page>> => {
    return axiosInstance.get(
      `/api/v1/comments/${commentId}/replies`,options
    );
  }
return {getComment,updateComment,deleteComment,getComments,createComment,getReplies}};
export type GetCommentResult = AxiosResponse<CommentDTO>
export type UpdateCommentResult = AxiosResponse<CommentDTO>
export type DeleteCommentResult = AxiosResponse<void>
export type GetCommentsResult = AxiosResponse<Page>
export type CreateCommentResult = AxiosResponse<CommentDTO>
export type GetRepliesResult = AxiosResponse<Page>
