/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  EchoGetParams
} from '../msocial.schemas';




  export const getEcho = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Эхо GET-запрос
 */
const echoGet = (
    params?: EchoGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.get(
      `/api/echo`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Эхо POST-запрос
 */
const echoPost = (
    echoPostBody: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/api/echo`,
      echoPostBody,{
    ...options,}
    );
  }
return {echoGet,echoPost}};
export type EchoGetResult = AxiosResponse<string>
export type EchoPostResult = AxiosResponse<string>
