/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';


export const getEchoGetResponseMock = (): string => (faker.word.sample())

export const getEchoPostResponseMock = (): string => (faker.word.sample())


export const getEchoGetMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.get('*/api/echo', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEchoGetResponseMock(),
      { status: 200
      })
  }, options)
}

export const getEchoPostMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/api/echo', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEchoPostResponseMock(),
      { status: 200
      })
  }, options)
}
export const getEchoMock = () => [
  getEchoGetMockHandler(),
  getEchoPostMockHandler()]
