/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';


export const getEchoGetResponseMock = (): string => (faker.word.sample())

export const getEchoPostResponseMock = (): string => (faker.word.sample())

