/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import type {
  AvatarDTO,
  UserDTO
} from '../msocial.schemas';


export const getGetProfileResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUpdateProfileResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUploadTrackResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUploadAvatarResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getGetAvatarHistoryResponseMock = (overrideResponse: Partial<Extract<AvatarDTO, object>> = {}): AvatarDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uploadedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getGetProfileByExternalIdResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

