/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AvatarDTO,
  UserDTO
} from '../msocial.schemas';


export const getGetProfileResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUpdateProfileResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUploadTrackResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUploadAvatarResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getGetAvatarHistoryResponseMock = (overrideResponse: Partial<Extract<AvatarDTO, object>> = {}): AvatarDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uploadedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getGetProfileByExternalIdResponseMock = (overrideResponse: Partial<Extract<UserDTO, object>> = {}): UserDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), externalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), personalInfo: faker.helpers.arrayElement([{birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favoriteTrackUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})


export const getGetProfileMockHandler = (overrideResponse?: UserDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserDTO> | UserDTO), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/users/profile', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProfileResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateProfileMockHandler = (overrideResponse?: UserDTO | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UserDTO> | UserDTO), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/users/profile', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateProfileResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUploadTrackMockHandler = (overrideResponse?: UserDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserDTO> | UserDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/users/profile/track', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadTrackResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUploadAvatarMockHandler = (overrideResponse?: UserDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserDTO> | UserDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/users/profile/avatar', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadAvatarResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAvatarHistoryMockHandler = (overrideResponse?: AvatarDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AvatarDTO> | AvatarDTO), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/users/profile/avatars', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAvatarHistoryResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetProfileByExternalIdMockHandler = (overrideResponse?: UserDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserDTO> | UserDTO), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/users/by-external-id/:externalId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProfileByExternalIdResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUsersMock = () => [
  getGetProfileMockHandler(),
  getUpdateProfileMockHandler(),
  getUploadTrackMockHandler(),
  getUploadAvatarMockHandler(),
  getGetAvatarHistoryMockHandler(),
  getGetProfileByExternalIdMockHandler()]
