/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AvatarDTO,
  ProfileUpdateRequest,
  UploadAvatarBody,
  UploadTrackBody,
  UserDTO
} from '../msocial.schemas';




  export const getUsers = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Получить профиль текущего пользователя
 */
const getProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDTO>> => {
    return axiosInstance.get(
      `/api/v1/users/profile`,options
    );
  }
/**
 * @summary Обновить профиль текущего пользователя
 */
const updateProfile = (
    profileUpdateRequest: ProfileUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDTO>> => {
    return axiosInstance.put(
      `/api/v1/users/profile`,
      profileUpdateRequest,options
    );
  }
/**
 * @summary Загрузить любимый трек
 */
const uploadTrack = (
    uploadTrackBody?: UploadTrackBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDTO>> => {const formData = new FormData();
if(uploadTrackBody?.file !== undefined) {
 formData.append(`file`, uploadTrackBody.file);
 }

    return axiosInstance.post(
      `/api/v1/users/profile/track`,
      formData,options
    );
  }
/**
 * @summary Загрузить аватар
 */
const uploadAvatar = (
    uploadAvatarBody?: UploadAvatarBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDTO>> => {const formData = new FormData();
if(uploadAvatarBody?.file !== undefined) {
 formData.append(`file`, uploadAvatarBody.file);
 }

    return axiosInstance.post(
      `/api/v1/users/profile/avatar`,
      formData,options
    );
  }
/**
 * @summary Получить историю аватаров
 */
const getAvatarHistory = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AvatarDTO>> => {
    return axiosInstance.get(
      `/api/v1/users/profile/avatars`,options
    );
  }
return {getProfile,updateProfile,uploadTrack,uploadAvatar,getAvatarHistory}};
export type GetProfileResult = AxiosResponse<UserDTO>
export type UpdateProfileResult = AxiosResponse<UserDTO>
export type UploadTrackResult = AxiosResponse<UserDTO>
export type UploadAvatarResult = AxiosResponse<UserDTO>
export type GetAvatarHistoryResult = AxiosResponse<AvatarDTO>
