/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Page,
  PostDTO
} from '../msocial.schemas';


export const getGetPostResponseMock = (overrideResponse: Partial<Extract<PostDTO, object>> = {}): PostDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), published: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUpdatePostResponseMock = (overrideResponse: Partial<Extract<PostDTO, object>> = {}): PostDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), published: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getCreatePostResponseMock = (overrideResponse: Partial<Extract<PostDTO, object>> = {}): PostDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), published: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getPublishPostResponseMock = (overrideResponse: Partial<Extract<PostDTO, object>> = {}): PostDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), published: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getAddPostMediaResponseMock = (overrideResponse: Partial<Extract<PostDTO, object>> = {}): PostDTO => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), authorId: faker.helpers.arrayElement([faker.number.int(), undefined]), authorName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), published: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getGetFeedResponseMock = (overrideResponse: Partial<Extract<Page, object>> = {}): Page => ({totalElements: faker.helpers.arrayElement([faker.number.int(), undefined]), totalPages: faker.helpers.arrayElement([faker.number.int(), undefined]), first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), numberOfElements: faker.helpers.arrayElement([faker.number.int(), undefined]), pageable: faker.helpers.arrayElement([{paged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int(), undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), unpaged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), offset: faker.helpers.arrayElement([faker.number.int(), undefined])}, undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({})), undefined]), number: faker.helpers.arrayElement([faker.number.int(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getGetFeedByExternalIdResponseMock = (overrideResponse: Partial<Extract<Page, object>> = {}): Page => ({totalElements: faker.helpers.arrayElement([faker.number.int(), undefined]), totalPages: faker.helpers.arrayElement([faker.number.int(), undefined]), first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), numberOfElements: faker.helpers.arrayElement([faker.number.int(), undefined]), pageable: faker.helpers.arrayElement([{paged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int(), undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), unpaged: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), offset: faker.helpers.arrayElement([faker.number.int(), undefined])}, undefined]), sort: faker.helpers.arrayElement([{sorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), unsorted: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({})), undefined]), number: faker.helpers.arrayElement([faker.number.int(), undefined]), empty: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})


export const getGetPostMockHandler = (overrideResponse?: PostDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostDTO> | PostDTO), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/posts/:postId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePostMockHandler = (overrideResponse?: PostDTO | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PostDTO> | PostDTO), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/posts/:postId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeletePostMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/posts/:postId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getCreatePostMockHandler = (overrideResponse?: PostDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostDTO> | PostDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/posts', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePostResponseMock(),
      { status: 201
      })
  }, options)
}

export const getPublishPostMockHandler = (overrideResponse?: PostDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostDTO> | PostDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/posts/:postId/publish', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPublishPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAddPostMediaMockHandler = (overrideResponse?: PostDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostDTO> | PostDTO), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/posts/:postId/media', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddPostMediaResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetFeedMockHandler = (overrideResponse?: Page | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Page> | Page), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/users/:userId/posts', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetFeedResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetFeedByExternalIdMockHandler = (overrideResponse?: Page | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Page> | Page), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/users/by-external-id/:externalId/posts', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetFeedByExternalIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeletePostMediaMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/posts/:postId/media/:mediaId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getPostsMock = () => [
  getGetPostMockHandler(),
  getUpdatePostMockHandler(),
  getDeletePostMockHandler(),
  getCreatePostMockHandler(),
  getPublishPostMockHandler(),
  getAddPostMediaMockHandler(),
  getGetFeedMockHandler(),
  getGetFeedByExternalIdMockHandler(),
  getDeletePostMediaMockHandler()]
