/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddPostMediaBody,
  CreatePostRequest,
  Page,
  PostDTO,
  UpdatePostRequest
} from '../msocial.schemas';




  export const getPosts = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Получить пост по ID
 */
const getPost = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostDTO>> => {
    return axiosInstance.get(
      `/api/v1/posts/${postId}`,options
    );
  }
/**
 * @summary Обновить пост
 */
const updatePost = (
    postId: number,
    updatePostRequest: UpdatePostRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostDTO>> => {
    return axiosInstance.put(
      `/api/v1/posts/${postId}`,
      updatePostRequest,options
    );
  }
/**
 * @summary Удалить пост
 */
const deletePost = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/posts/${postId}`,options
    );
  }
/**
 * @summary Создать пост
 */
const createPost = (
    createPostRequest: CreatePostRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostDTO>> => {
    return axiosInstance.post(
      `/api/v1/posts`,
      createPostRequest,options
    );
  }
/**
 * @summary Опубликовать пост
 */
const publishPost = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostDTO>> => {
    return axiosInstance.post(
      `/api/v1/posts/${postId}/publish`,
      undefined,options
    );
  }
/**
 * @summary Добавить медиафайлы к посту
 */
const addPostMedia = (
    postId: number,
    addPostMediaBody?: AddPostMediaBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostDTO>> => {const formData = new FormData();
if(addPostMediaBody?.files !== undefined) {
 addPostMediaBody?.files.forEach(value => formData.append(`files`, value));
 }

    return axiosInstance.post(
      `/api/v1/posts/${postId}/media`,
      formData,options
    );
  }
/**
 * @summary Получить ленту постов пользователя
 */
const getFeed = (
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Page>> => {
    return axiosInstance.get(
      `/api/v1/users/${userId}/posts`,options
    );
  }
/**
 * @summary Получить ленту постов пользователя по externalId
 */
const getFeedByExternalId = (
    externalId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Page>> => {
    return axiosInstance.get(
      `/api/v1/users/by-external-id/${externalId}/posts`,options
    );
  }
/**
 * @summary Удалить медиафайл из поста
 */
const deletePostMedia = (
    postId: number,
    mediaId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/posts/${postId}/media/${mediaId}`,options
    );
  }
return {getPost,updatePost,deletePost,createPost,publishPost,addPostMedia,getFeed,getFeedByExternalId,deletePostMedia}};
export type GetPostResult = AxiosResponse<PostDTO>
export type UpdatePostResult = AxiosResponse<PostDTO>
export type DeletePostResult = AxiosResponse<void>
export type CreatePostResult = AxiosResponse<PostDTO>
export type PublishPostResult = AxiosResponse<PostDTO>
export type AddPostMediaResult = AxiosResponse<PostDTO>
export type GetFeedResult = AxiosResponse<Page>
export type GetFeedByExternalIdResult = AxiosResponse<Page>
export type DeletePostMediaResult = AxiosResponse<void>
