/**
 * msocial SDK
 * Generated by orval. Auto-generated API client for msocial.
 */

export * from './msocial.schemas';

export * from './auth/auth';
export * from './comments/comments';
export * from './echo/echo';
export * from './posts/posts';
export * from './users/users';

export { default as axios } from 'axios';
export type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
