/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
/**
 * Запрос на обновление профиля
 */
export interface ProfileUpdateRequest {
  /** День рождения */
  birthDate?: string;
  /**
     * Адрес
     * @minLength 0
     * @maxLength 500
     */
  address?: string;
  /**
     * Статус
     * @minLength 0
     * @maxLength 255
     */
  status?: string;
}

/**
 * Персональная информация пользователя
 */
export interface PersonalInfoDTO {
  /** День рождения */
  birthDate?: string;
  /** Адрес */
  address?: string;
  /** Ссылка на любимый трек */
  favoriteTrackUrl?: string;
  /** Статус */
  status?: string;
}

/**
 * Профиль пользователя
 */
export interface UserDTO {
  /** Локальный идентификатор */
  id?: number;
  /** Внешний Matrix ID */
  externalId?: string;
  /** Персональная информация */
  personalInfo?: PersonalInfoDTO;
  /** Дата создания */
  createdAt?: string;
}

/**
 * Ответ при ошибке
 */
export interface ErrorResponse {
  /** Код ошибки */
  code?: string;
  /** Сообщение об ошибке */
  message?: string;
}

/**
 * Запрос на обновление поста
 */
export interface UpdatePostRequest {
  /**
     * Содержимое поста
     * @minLength 0
     * @maxLength 5000
     */
  content: string;
}

/**
 * Медиафайл поста
 */
export interface PostMediaDTO {
  /** Идентификатор медиа */
  id?: number;
  /** URL медиафайла */
  url?: string;
  /** Порядок сортировки */
  sortOrder?: number;
}

/**
 * Пост
 */
export interface PostDTO {
  /** Идентификатор поста */
  id?: number;
  /** Идентификатор автора */
  authorId?: number;
  /** Имя автора (внешний Matrix ID) */
  authorName?: string;
  /** Содержимое поста */
  content?: string;
  /** Медиафайлы поста */
  media?: PostMediaDTO[];
  /** Опубликован */
  published?: boolean;
  /** Дата создания */
  createdAt?: string;
}

/**
 * Запрос на обновление комментария
 */
export interface UpdateCommentRequest {
  /**
     * Новое содержимое комментария
     * @minLength 0
     * @maxLength 2000
     */
  content: string;
}

/**
 * Статус комментария
 */
export type CommentDTOStatus = typeof CommentDTOStatus[keyof typeof CommentDTOStatus];


export const CommentDTOStatus = {
  PUBLISHED: 'PUBLISHED',
  DELETED: 'DELETED',
  HIDDEN: 'HIDDEN',
} as const;

/**
 * Комментарий
 */
export interface CommentDTO {
  /** Идентификатор комментария */
  id?: number;
  /** Идентификатор поста */
  postId?: number;
  /** Идентификатор автора */
  authorId?: number;
  /** Имя автора (внешний Matrix ID) */
  authorName?: string;
  /** Идентификатор родительского комментария (для ответов) */
  parentId?: number;
  /** Содержимое комментария */
  content?: string;
  /** Статус комментария */
  status?: CommentDTOStatus;
  /** Дата создания */
  createdAt?: string;
  /** Дата последнего обновления */
  updatedAt?: string;
}

/**
 * Запрос на создание поста
 */
export interface CreatePostRequest {
  /**
     * Содержимое поста
     * @minLength 0
     * @maxLength 5000
     */
  content: string;
}

/**
 * Запрос на создание комментария
 */
export interface CreateCommentRequest {
  /**
     * Содержимое комментария
     * @minLength 0
     * @maxLength 2000
     */
  content: string;
  /** Идентификатор родительского комментария (для ответов) */
  parentId?: number;
}

/**
 * Запрос на обновление пары токенов
 */
export interface RefreshRequest {
  /**
     * Действующий refresh-токен
     * @minLength 1
     */
  refreshToken: string;
}

/**
 * Ответ с токенами доступа
 */
export interface AuthResponse {
  /** JWT access-токен */
  accessToken?: string;
  /** Refresh-токен для обновления сессии */
  refreshToken?: string;
  /** Время жизни access-токена в секундах */
  expiresIn?: number;
}

/**
 * Запрос на аутентификацию через Matrix OpenID
 */
export interface LoginRequest {
  /**
     * Токен, полученный от Matrix-сервера
     * @minLength 1
     */
  openidToken: string;
  /** Идентификатор пользователя (используется только в dev-режиме при отключённой верификации) */
  userId?: string;
}

export interface SortObject {
  sorted?: boolean;
  unsorted?: boolean;
  empty?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: SortObject;
  unpaged?: boolean;
  offset?: number;
}

export interface Page {
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  sort?: SortObject;
  size?: number;
  content?: unknown[];
  number?: number;
  empty?: boolean;
}

/**
 * Аватар пользователя
 */
export interface AvatarDTO {
  /** Идентификатор аватара */
  id?: number;
  /** URL аватара */
  url?: string;
  /** Дата загрузки */
  uploadedAt?: string;
  /** Активен ли аватар */
  active?: boolean;
}

export interface JwtClaims {
  sub?: string;
  roles?: string[];
  sessionId?: number;
}

export type UploadTrackBody = {
  /** Аудиофайл трека */
  file: Blob;
};

export type UploadAvatarBody = {
  /** Файл аватара (изображение) */
  file: Blob;
};

export type AddPostMediaBody = {
  /** Медиафайлы для загрузки */
  files: Blob[];
};

export type EchoGetParams = {
/**
 * Сообщение для возврата
 */
message?: string;
};

