/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AuthResponse,
  JwtClaims
} from '../msocial.schemas';


export const getRefreshResponseMock = (overrideResponse: Partial<Extract<AuthResponse, object>> = {}): AuthResponse => ({accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expiresIn: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getLoginResponseMock = (overrideResponse: Partial<Extract<AuthResponse, object>> = {}): AuthResponse => ({accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expiresIn: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getValidateTokenResponseMock = (overrideResponse: Partial<Extract<JwtClaims, object>> = {}): JwtClaims => ({sub: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roles: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), sessionId: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})


export const getRefreshMockHandler = (overrideResponse?: AuthResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AuthResponse> | AuthResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshResponseMock(),
      { status: 200
      })
  }, options)
}

export const getLogoutMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/logout', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getLoginMockHandler = (overrideResponse?: AuthResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AuthResponse> | AuthResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getValidateTokenMockHandler = (overrideResponse?: JwtClaims | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<JwtClaims> | JwtClaims), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/auth/validate', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getValidateTokenResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAuthMock = () => [
  getRefreshMockHandler(),
  getLogoutMockHandler(),
  getLoginMockHandler(),
  getValidateTokenMockHandler()]
