/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponse,
  JwtClaims,
  LoginRequest,
  RefreshRequest
} from '../msocial.schemas';




  export const getAuth = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Обновление токенов
 */
const refresh = (
    refreshRequest: RefreshRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    return axiosInstance.post(
      `/api/v1/auth/refresh`,
      refreshRequest,options
    );
  }
/**
 * @summary Выход из системы
 */
const logout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/logout`,
      undefined,options
    );
  }
/**
 * @summary Вход по Matrix OpenID токену
 */
const login = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }
/**
 * @summary Валидация access-токена
 */
const validateToken = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<JwtClaims>> => {
    return axiosInstance.get(
      `/api/v1/auth/validate`,options
    );
  }
return {refresh,logout,login,validateToken}};
export type RefreshResult = AxiosResponse<AuthResponse>
export type LogoutResult = AxiosResponse<void>
export type LoginResult = AxiosResponse<AuthResponse>
export type ValidateTokenResult = AxiosResponse<JwtClaims>
