/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * msocial API
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import type {
  AuthResponse,
  JwtClaims
} from '../msocial.schemas';


export const getRefreshResponseMock = (overrideResponse: Partial<Extract<AuthResponse, object>> = {}): AuthResponse => ({accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expiresIn: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getLoginResponseMock = (overrideResponse: Partial<Extract<AuthResponse, object>> = {}): AuthResponse => ({accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expiresIn: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getValidateTokenResponseMock = (overrideResponse: Partial<Extract<JwtClaims, object>> = {}): JwtClaims => ({sub: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roles: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), sessionId: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

